services:
  api:
    build: ./api
    ports:
      - "8000:8000"
    depends_on:
      - redis
  worker:
    build: ./worker
    ports:
      - "8001:8001"
    depends_on:
      - redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  alertmanager:
    image: prom/alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml